import type { Metadata } from "next";
import { Bebas_Neue, Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { ProjectsProvider } from "@/contexts/ProjectsContext";

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas-neue",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "SlideStudio v2 — TikTok Slide Creator",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if this is an export route - skip auth providers for Puppeteer
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || headersList.get("referer") || "";
  const isExportRoute = pathname.includes("/export/");

  return (
    <html lang="en" className="dark">
      <body
        className={`${bebasNeue.variable} ${plusJakartaSans.variable} ${jetbrainsMono.variable} antialiased`}
      >
        {isExportRoute ? (
          // Export routes don't need auth - they're token-protected
          children
        ) : (
          // Regular routes need auth providers
          <UserProvider>
            <ProjectsProvider>
              {children}
            </ProjectsProvider>
          </UserProvider>
        )}
      </body>
    </html>
  );
}
